<a href="https://colab.research.google.com/github/ghddusghk46/dlp/blob/main/inlcass/week02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

#create a placeholder of type float 34-bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])

#create a constant of type float 34-bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)

#use the placeholder as you would a constant or a varable
#c = a + b
#short for

c= tf.add(a, b)

with tf.Session() as sess:
  #feed [1, 2, 3] to place holder a via the dict {a: [1, 2, 3]}
  #fetch value of c
  print(sess.run(c, {a: [1, 2, 3]}))

[6. 7. 8.]


In [22]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)

addOperation = tf.matmul(a, b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a: [[1, 2, 3], [1, 2, 3], [1, 2, 3]], b: [[1, 2, 3], [1, 2, 3], [1, 2, 3]]}))

[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


In [9]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.float32)
b = tf.constant([5, 5, 5], tf.float32)
addOperation = tf.add(a, b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a: [1, 2, 3]}))

[6. 7. 8.]


In [20]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant([5, 5, 5], tf.float32) # tf.placeholder(tf.float32)
b = tf.constant([5, 5, 5], tf.float32) # tf.placeholder(tf.float32)

x1 = tf.add(a, b) # +
x2 = tf.subtract(a, b) # -
x3 = tf.multiply(a, b) # *
x4 = tf.divide(a, b) # %

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(x1, {a:[10, 20, 30], b:[1, 2, 3]}))
  print(sess.run(x2, {a:[10, 20, 30], b:[1, 2, 3]}))
  print(sess.run(x3, {a:[10, 20, 30], b:[1, 2, 3]}))
  print(sess.run(x4, {a:[10, 20, 30], b:[1, 2, 3]}))

[11. 22. 33.]
[ 9. 18. 27.]
[10. 40. 90.]
[10. 10. 10.]


In [30]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
addOperation = tf.matmul(a, b) # 행렬곱

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a: [[5, 10, 20], [1, 5, 7], [55, 100, 200]], b: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]}))
  print(sess.run(addOperation, {a: [[5, 10, 20], [10, 20, 30], [1, 2, 3]], b: [[1], [2], [3]]}))

[[ 185.  220.  255.]
 [  70.   83.   96.]
 [1855. 2210. 2565.]]
[[ 85.]
 [140.]
 [ 14.]]


In [34]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# x = 10
x = tf.Variable(10, name = "x")

# y = 20
y = tf.Variable(20, name = "y")

# x1 = x + y = 30
z1 = tf.add(x, y, name = "z1")

# z2 = x * y = 200
z2 = tf.multiply(x, y, name = "z2")

# z3 = z1 * z2 = 6000
z3 = tf.multiply(z1, z2, name = "z3")

init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  writer = tf.summary.FileWriter('./graphs', sess.graph)
  # y = tf.Variable(1)로 y값을 1로 바꾸어도 placeholder가 아니고 아래에서부터 위로 진행되기 때문에 y값이 바뀌지 않고 계산된다.
  print(sess.run(z3))

  writer.close()

6000
